### PR TITLE
fix: replace fast-atomic-write with steno

### LINKED ISSUE #284: feat: replace fast-write-atomic with steno
See https://github.com/SgtPooki/fast-write-atomic#uint8array

| Task Name                                             | ops/sec | Average Time (ns)  | Margin | Samples |
|-------------------------------------------------------|---------|--------------------|--------|---------|
| Uint8Array - write-file-atomic                        | 101     | 9853620.467916131  | ±1.15% | 1000    |
| Uint8Array - fast-write-atomic                        | 106     | 9421993.666924536  | ±1.30% | 1000    |
| Uint8Array - atomically                               | 101     | 9857824.475903064  | ±1.16% | 1000    |
| Uint8Array - steno                                    | 2,937   | 340472.6759530604  | ±4.23% | 1000    |
| Uint8Array - steno (cached writers)                   | 3,037   | 329200.16099512577 | ±6.35% | 1000    |
| Uint8Array - @sgtpooki/steno-patched                  | 2,940   | 340053.3969886601  | ±9.02% | 1000    |
| Uint8Array - @sgtpooki/steno-patched (cached writers) | 2,566   | 389624.0490563214  | ±8.57% | 1000    |

```[tasklist]
### Tasks
- [x] update steno to support more than strings (it should support everything fsPromises.writeFile supports) - see https://github.com/SgtPooki/steno
- [x] replace https://github.com/ipfs/js-stores/blob/7dad9a43fdec367895467752a6fee3ac7f912ca4/packages/blockstore-fs/src/index.ts#L22
- [x] replace https://github.com/ipfs/js-stores/blob/7dad9a43fdec367895467752a6fee3ac7f912ca4/packages/datastore-fs/src/index.ts#L22
```

related: https://github.com/ipfs/helia/pull/346#issuecomment-1856615727

### PR DESCRIPTION
**Pull request by SgtPooki**
fixes #284

fast-write-atomic hasn't been updated in 5 years, is CJS, and is slower than steno (updated 2 months ago).

Benchmarks for various content-types & libraries (though we only use Uint8Arrays) can be found at https://github.com/SgtPooki/fast-write-atomic#benchmarks

However, there may be further room for improvement by moving to [fs.createWriteStream](https://nodejs.org/api/fs.html#fscreatewritestreampath-options)

```
╰─ ✔ ❯ hyperfine --parameter-list branch 284-chore-replace-fast-write-atomic-with-steno,main --setup "git switch {branch} && npm run reset && npm i && npm run build" --runs 20  -w 1 "npm run test:node"
Benchmark 1: npm run test:node (branch = 284-chore-replace-fast-write-atomic-with-steno)
  Time (mean ± σ):     27.212 s ±  0.832 s    [User: 34.810 s, System: 6.051 s]
  Range (min … max):   25.927 s … 29.324 s    20 runs

Benchmark 2: npm run test:node (branch = main)
  Time (mean ± σ):     42.971 s ±  0.637 s    [User: 35.297 s, System: 7.534 s]
  Range (min … max):   42.178 s … 44.796 s    20 runs

Summary
  npm run test:node (branch = 284-chore-replace-fast-write-atomic-with-steno) ran
    1.58 ± 0.05 times faster than npm run test:node (branch = main)
```

---

### Updated benchmarks of `npm run test` as of 2024-04-19

```
╭─    ~/code/work/protocol.ai/ipfs/js-stores    main ?1 
╰─ ✔ ❯ hyperfine --parameter-list branch main,test/not-same-event-loop-concurrency,284-chore-replace-fast-write-atomic-with-steno --setup "git switch {branch} && npm run reset && npm i && npm run build && cd packages/datastore-fs" "npm run test"
Benchmark 1: npm run test (branch = main)
  Time (mean ± σ):     99.415 s ±  2.918 s    [User: 69.659 s, System: 23.361 s]
  Range (min … max):   96.134 s … 105.200 s    10 runs

Benchmark 2: npm run test (branch = test/not-same-event-loop-concurrency)
  Time (mean ± σ):     103.456 s ±  3.186 s    [User: 74.442 s, System: 25.261 s]
  Range (min … max):   98.813 s … 108.429 s    10 runs

Benchmark 3: npm run test (branch = 284-chore-replace-fast-write-atomic-with-steno)
  Time (mean ± σ):     80.308 s ±  2.107 s    [User: 74.331 s, System: 22.228 s]
  Range (min … max):   78.219 s … 84.277 s    10 runs

Summary
  npm run test (branch = 284-chore-replace-fast-write-atomic-with-steno) ran
    1.24 ± 0.05 times faster than npm run test (branch = main)
    1.29 ± 0.05 times faster than npm run test (branch = test/not-same-event-loop-concurrency)                                                                                        [49m1.944s]

╭─    ~/code/work/protocol.ai/ipfs/js-stores    284-chore-re…c-with-steno ?1 
╰─ ✔ ❯ hyperfine --parameter-list branch main,test/not-same-event-loop-concurrency,284-chore-replace-fast-write-atomic-with-steno --setup "git switch {branch} && npm run reset && npm i && npm run build && cd packages/blockstore-fs" "npm run test"
Benchmark 1: npm run test (branch = main)
  Time (mean ± σ):     98.840 s ±  2.612 s    [User: 68.486 s, System: 22.585 s]
  Range (min … max):   97.005 s … 104.396 s    10 runs

Benchmark 2: npm run test (branch = test/not-same-event-loop-concurrency)
  Time (mean ± σ):     105.307 s ±  2.335 s    [User: 72.442 s, System: 24.766 s]
  Range (min … max):   101.167 s … 109.007 s    10 runs

Benchmark 3: npm run test (branch = 284-chore-replace-fast-write-atomic-with-steno)
  Time (mean ± σ):     77.012 s ±  1.829 s    [User: 74.442 s, System: 21.938 s]
  Range (min … max):   75.258 s … 80.825 s    10 runs

Summary
  npm run test (branch = 284-chore-replace-fast-write-atomic-with-steno) ran
    1.28 ± 0.05 times faster than npm run test (branch = main)
    1.37 ± 0.04 times faster than npm run test (branch = test/not-same-event-loop-concurrency)
```

### CODE REVIEW

File: packages/blockstore-fs/src/index.ts [hunk 1]
```diff
@@ -151,8 +149,16 @@ export class FsBlockstore implements Blockstore {
...
+
+      let writer = this.writers.get(filePath)
+      if (writer == null) {
+        writer = new StenoWriter(filePath)
+        this.writers.set(filePath, writer)
+      }
 
-      await writeFile(path.join(this.path, dir, file), val)
+      await writeFile(writer, filePath, val)
+      this.writers.delete(filePath)
```
Comment (achingbrain) [inline packages/blockstore-fs/src/index.ts:161]: I think this introduces a race condition.  If I try to write the same block from three different contexts, A, B and C

1. A does `this.writers.get`, it returns `null`, A does `this.writers.set`, starts `await writeFile`
2. B does `this.writers.get`, it returns `StenoWriter`, B starts `await writeFile`
3. A finishes `await writeFile`, A does `this.writers.delete`
4. C does `this.writers.get`, it returns `null`, C does `this.writers.set` starts `await writeFile`
5. B & C are now fighting: 💥 

You can fix this by using a reference count:

`this.writers` becomes `Map<string, { refs: number, writer: StenoWriter }>`

1. A does `this.writers.get`, it returns `null`, A does `this.writers.set` with refs 1, starts `await writeFile`
2. B does `this.writers.get`, it returns `StenoWriter`, B increments refs to 2, B starts `await writeFile`
3. A finishes `await writeFile`, A decrements refs, refs is 1
4. C does `this.writers.get`, it returns `StenoWriter`, C increments refs to 2, C starts `await writeFile`
5. B finishes `await writeFile`, A decrements refs, refs is 1
6. C finishes `await writeFile`, A decrements refs, refs is 0, C does `this.writers.delete`

There's also a memory leak - handling decrementing refs and removing things from `this.writers` needs to be done in a  `finally` block because if the call to `writeFile` throws, the `StenoWriter` will never be removed from `this.writers`.

The final thing is that if we have multiple processes waiting for for the writes of other processes to complete like this we may want to accept an `AbortOptions` and then use [race-signal](https://www.npmjs.com/package/race-signal) to allow callers to break out of any deadlocks that might occur.

File: packages/blockstore-fs/src/index.ts [hunk 2]
```diff
@@ -14,12 +14,10 @@
 
 import fs from 'node:fs/promises'
 import path from 'node:path'
-import { promisify } from 'node:util'
+import { Writer as StenoWriter } from '@sgtpooki/steno-patched'
```
Comment (achingbrain) [inline packages/blockstore-fs/src/index.ts:17]: Can you please PR steno with the improvements?  It would be good to not depend on forks where possible.

File: packages/blockstore-fs/src/index.ts [hunk 3]
```diff
@@ -28,20 +26,19 @@ import type { Blockstore, Pair } from 'interface-blockstore'
...
-    await writeAtomic(file, contents)
+    await writer.write(contents)
   } catch (err: any) {
     if (err.code === 'EPERM' && err.syscall === 'rename') {
-      // fast-write-atomic writes a file to a temp location before renaming it.
+      // steno writes a file to a temp location before renaming it.
       // On Windows, if the final file already exists this error is thrown.
       // No such error is thrown on Linux/Mac
       // Make sure we can read & write to this file
+      // 2023-12-14: Is this still needed with steno?
```
Comment (achingbrain) [inline packages/blockstore-fs/src/index.ts:41]: This block handles the case where two processes (e.g. two [cluster](https://nodejs.org/api/cluster.html) workers) are using the same blockstore and try to write the same block simultaneously.

Steno [doesn't handle this](https://github.com/typicode/steno/issues/3), so I think yes.

Something like `flock` from [fs-ext](https://www.npmjs.com/package/fs-ext) might be better here (mentioned in the linked issue), since it uses the filesystem for locking instead of holding it in-process, though I've no idea about Windows support there.

**Review by achingbrain — CHANGES_REQUESTED** [review]

File: packages/blockstore-fs/src/index.ts (hunk 2 above)
Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:17]: Yep, its out there: https://github.com/typicode/steno/pull/32

Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:17]: By the way, after running the benchmarks mentioned in the description, I verified steno supports the different content types already so that we could use steno now with a `ts-expect-error`

File: packages/blockstore-fs/src/index.ts (hunk 3 above)
Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:41]: I'll add `flock` from `fs-ext` to https://github.com/SgtPooki/fast-write-atomic#benchmarks and see what happens

Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:41]: we should also make sure we have a test for this.. i'll see about adding one

File: packages/blockstore-fs/src/index.ts (hunk 1 above)
Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:161]: we should have a failing test for this.. i'll see about adding one

File: packages/blockstore-fs/src/index.ts (hunk 3 above)
Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:41]: FYI i've been doing some testing, and fast-write-atomic doesn't seem to be concurrency safe either, but i've got a modified steno that is now with fs-ext, though there are some issues with windows support there.

It's slower than steno, but still significantly faster than write-file-atomic and actually thread safe (as far as fs-ext.flock supports at least), but locking/unlocking is expected to increase some slowness. I added pRetry to retry the fs-ext locking, so that has some slight overhead too. Currently set retries to 1000, but real-world usecase could probably support retry of 100 (retry of 100 fails in my cluster test)

bench results for strings:

| Task Name                        | ops/sec | Average Time (ns)  | Margin | Samples |
|----------------------------------|---------|--------------------|--------|---------|
| string - write-file-atomic       | 98      | 10200464.169681072 | ±3.15% | 100     |
| string - fast-write-atomic       | 87      | 11492403.77008915  | ±2.62% | 100     |
| string - atomically              | 93      | 10701752.150654793 | ±3.81% | 100     |
| string - steno                   | 1,697   | 589000.475877025   | ±3.44% | 849     |
| string - @sgtpooki/steno-patched | 1,662   | 601492.9283768511  | ±4.86% | 832     |
| string - steno-custom.js         | 721     | 1385954.2634678679 | ±4.82% | 361     |

---

I'm going to see if I can wiggle my test into this library, but if you want to take a peek it's at https://github.com/SgtPooki/fast-write-atomic/blob/testing-concurrent/test-cluster-write.mjs

Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:41]: Here's a test run of the cluster concurrency test:

```console
> node test-cluster-write.mjs 
Primary 59413 has started.
Worker 59418 has started.
Worker 59414 has started.
Worker 59419 has started.
Worker 59416 has started.
Worker 59420 has started.
Worker 59417 has started.
Worker 59415 has started.
Worker 59423 has started.
Worker 59421 has started.
Worker 59422 has started.
testing write of large string of length 107465

testing fwaWrite..........
file contents mismatch for fwaWrite
expected test-data-59417-1pzm...
got test-data-59423-1pzm...

testing stenoWrite.worker 59420 threw an error when trying to write file with stenoWrite
worker 59417 threw an error when trying to write file with stenoWrite
worker 59421 threw an error when trying to write file with stenoWrite
worker 59422 threw an error when trying to write file with stenoWrite
worker 59419 threw an error when trying to write file with stenoWrite
worker 59423 threw an error when trying to write file with stenoWrite
worker 59416 threw an error when trying to write file with stenoWrite
worker 59418 threw an error when trying to write file with stenoWrite
worker 59414 threw an error when trying to write file with stenoWrite

file contents mismatch for stenoWrite
expected test-data-59414-1pzm...
got test-data-59418-1pzm...

testing customStenoWrite....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
testing manualWrite..........
file contents mismatch for manualWrite
expected test-data-59415-1pzm...
got test-data-59417-1pzm...

testing manualWriteFd....................
file contents mismatch for manualWriteFd
expected test-data-59423-1pzm...
got test-data-59421-1pzm...

Primary 59413 is exiting.
The following write functions failed concurrent write test:
         * fwaWrite
         * stenoWrite
         * manualWrite
         * manualWriteFd 
```

Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:41]: I just tested this on windows, and the custom-steno.mjs passes there as well as manualWrite and manualWrite with file-descriptors:


```
The following write functions failed concurrent write test:
         * fwaWrite
         * stenoWrite
```

File: packages/blockstore-fs/src/index.ts (hunk 2 above)
Comment (achingbrain) [reply packages/blockstore-fs/src/index.ts:17]: It looks like your patch got merged, this can probably revert to regular `steno` now?

Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts]: this is done as of [`57048de` (#285)](https://github.com/ipfs/js-stores/pull/285/commits/57048debcdd2efb771e77d806231dd9c22538aeb)

File: packages/blockstore-fs/src/index.ts (hunk 3 above)
Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:41]: [a test for concurrent writing](https://github.com/search?q=repo%3Aipfs%2Fjs-stores%20can%20survive%20concurrent%20writes&type=code) already exists but i'm not sure it's testing full multi-cluster/process concurrency because all of the writes are handled by the same event loop.

I've got another test on main thread i'm going to add and then rebase this PR on top of it.

Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:41]: created in https://github.com/ipfs/js-stores/pull/305

File: packages/blockstore-fs/src/index.ts (hunk 1 above)
Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:159]: Idk about testing for a race condition here other than the other concurrency tests we already have, but I did a ton of testing on [the other large comment thread](https://github.com/ipfs/js-stores/pull/285#discussion_r1427926375) and it seems like caching writers doesn't even give us a benefit, so I'll remove all this complexity entirely and see that it still passes tests (including https://github.com/ipfs/js-stores/pull/305)

**Review by wemeetagain — APPROVED** [review]

**Comment by SgtPooki** [comment]
@achingbrain anything else needed for this one or can I merge it?

File: packages/blockstore-fs/src/index.ts [hunk 4]
```diff
@@ -14,28 +14,25 @@
...
  * Write a file atomically
  */
 async function writeFile (file: string, contents: Uint8Array): Promise<void> {
   try {
-    await writeAtomic(file, contents)
+    const writer = new Writer(file)
+    await writer.write(contents)
   } catch (err: any) {
     if (err.syscall === 'rename' && ['ENOENT', 'EPERM'].includes(err.code)) {
       // fast-write-atomic writes a file to a temp location before renaming it.
```
Comment (achingbrain) [inline packages/blockstore-fs/src/index.ts:38]: Given that we no longer use fwa is this error detection still necessary?

File: packages/datastore-fs/src/index.ts [hunk 5]
```diff
@@ -14,28 +14,25 @@
...
  * Write a file atomically
  */
 async function writeFile (path: string, contents: Uint8Array): Promise<void> {
   try {
-    await writeAtomic(path, contents)
+    const writer = new Writer(path)
+    await writer.write(contents)
   } catch (err: any) {
     if (err.syscall === 'rename' && ['ENOENT', 'EPERM'].includes(err.code)) {
       // fast-write-atomic writes a file to a temp location before renaming it.
```
Comment (achingbrain) [inline packages/datastore-fs/src/index.ts:38]: Same comment as https://github.com/ipfs/js-stores/pull/285/files#r1693365294

**Review by achingbrain — CHANGES_REQUESTED** [review]
LGTM, just the question over the error detection we used to do for fast-write-atomic.

File: packages/blockstore-fs/src/index.ts (hunk 4 above)
Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:38]: @achingbrain steno also writes to a temp file before renaming it to the new one. I looked into this a while back but haven't in a while. let me double check if https://github.com/ipfs/js-stores/pull/305 still passes when removing this error handling

Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:38]: fails with 

```
  2 passing (1s)
  1 failing

  1) FsBlockstore
       can survive concurrent writes:
     Error: ENOENT: no such file or directory, rename '/var/folders/bl/_gl5_59s11v7qz5ysd6bfgb00000gn/T/test-0.1889829891040602/LY/.BCIQPGZJ6QLZOFG3OP45NLMSJUWGJCO72QQKHLDTB6FXIB6BDSLRQYLY.data.tmp' -> '/var/folders/bl/_gl5_59s11v7qz5ysd6bfgb00000gn/T/test-0.1889829891040602/LY/BCIQPGZJ6QLZOFG3OP45NLMSJUWGJCO72QQKHLDTB6FXIB6BDSLRQYLY.data'
      at rename (node:internal/fs/promises:782:10)
      at file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/node_modules/steno/lib/index.js:55:17
      at retryAsyncOperation (file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/node_modules/steno/lib/index.js:14:20)
      at Writer.#write (file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/node_modules/steno/lib/index.js:54:13)
      at writeFile (file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/packages/blockstore-fs/src/index.ts:35:5)
      at FsBlockstore.put (file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/packages/blockstore-fs/src/index.ts:151:7)
      at file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/packages/blockstore-fs/test/index.spec.ts:155:48
      at async Promise.all (index 3)
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/packages/blockstore-fs/test/index.spec.ts:154:5)
```

Comment (SgtPooki) [reply packages/blockstore-fs/src/index.ts:38]: So yes, we still need this. I will update the comment

File: packages/datastore-fs/src/index.ts (hunk 5 above)
Comment (SgtPooki) [reply packages/datastore-fs/src/index.ts]: yea it's needed. I updated the comment itself

**Review by achingbrain — APPROVED** [review]
